from .home import HomePage
from .stream_control import StreamControlPage
from .media_player import MediaPlayerPage
from .background_music import BackgroundMusicPage
from .chat_center import ChatCenterPage
from .ai_producer import AIProducerPage
from .authorization import AuthorizationPage
from .designer import DesignerPage
from .settings import SettingsPage
from .logs import LogsPage
from .updates import UpdatesPage
from .help import HelpPage
from .developer import DeveloperPage
from .about import AboutPage
