param([Parameter(Mandatory=$true)][string]$ArtifactDir)
$ErrorActionPreference='Stop'
$base='.\optimizer\scripts\r54_2_game_mutation_acceptance_v2.ps1'
$src=Get-Content $base -Raw
$start=$src.IndexOf('$navNew=@''',[StringComparison]::Ordinal)
if($start-lt0){throw 'R54.2 v4 nav block start missing'}
$end=$src.IndexOf("'@.Trim()",$start,[StringComparison]::Ordinal)
if($end-lt0){throw 'R54.2 v4 nav block end missing'}
$end += "'@.Trim()".Length
$b64='JG5hdk5ldz1AJwojIFByZWZlciB0aGUgcmVhbCBkYXNoYm9hcmQgYWN0aW9uIGJ1dHRvbi4gSXQgcmVhY2hlcyB0aGUgc2FtZSBCdWlsZHMgcGFnZSBidXQKIyBleHBvc2VzIGEgcHJvcGVyIEludm9rZVBhdHRlcm4gb24gaG9zdGVkIFdpbmRvd3MsIHVubGlrZSB0aGUgc2lkZWJhciBUZXh0QmxvY2suCiRvcGVuQnVpbGRzPUZpbmQtTmFtZUNvbnRhaW5zICRtYWluICfQktGL0LHRgNCw0YLRjCDRgdCx0L7RgNC60YMnCmlmKCEkb3BlbkJ1aWxkcyl7JG9wZW5CdWlsZHM9RmluZC1OYW1lQ29udGFpbnMgJG1haW4gJ9Ch0LHQvtGA0LrQuCd9CmlmKCEoSW52b2tlLUVsZW1lbnQgJG9wZW5CdWlsZHMpKXt0cnl7JHByb2MuS2lsbCgpfWNhdGNoe307dGhyb3cgJ1I1NC4yIEdBTUUgY291bGQgbm90IG9wZW4gQnVpbGRzIHBhZ2UnfQokZGVhZGxpbmVQYWdlPShHZXQtRGF0ZSkuQWRkU2Vjb25kcyg4KQokcGFnZVJlYWR5PSRmYWxzZQp3aGlsZSgoR2V0LURhdGUpLWx0JGRlYWRsaW5lUGFnZSAtYW5kICEkcGFnZVJlYWR5KXsKICAgIFN0YXJ0LVNsZWVwIC1NaWxsaXNlY29uZHMgMzUwCiAgICBmb3JlYWNoKCRjYW5kaWRhdGUgaW4gKEdldC1Qcm9jZXNzV2luZG93cyAkcHJvYy5JZCkpewogICAgICAgICRjYW5kaWRhdGVUZXh0PVdpbmRvdy1UZXh0ICRjYW5kaWRhdGUKICAgICAgICBpZigkY2FuZGlkYXRlVGV4dCAtbWF0Y2ggJ9Ch0LHQvtGA0LrQuCBXaW5kb3dzJyAtYW5kICRjYW5kaWRhdGVUZXh0IC1tYXRjaCAn0JLRi9Cx0YDQsNGC0YwgR0FNRScpeyRtYWluPSRjYW5kaWRhdGU7JHBhZ2VSZWFkeT0kdHJ1ZTticmVha30KICAgIH0KfQppZighJHBhZ2VSZWFkeSl7CiAgICAkdHh0PVdpbmRvdy1UZXh0ICRtYWluCiAgICB0cnl7JHByb2MuS2lsbCgpfWNhdGNoe30KICAgIHRocm93ICJSNTQuMiBHQU1FIEJ1aWxkcyBwYWdlIGRpZCBub3QgYmVjb21lIHJlYWR5LiBVST0kdHh0Igp9CldyaXRlLUhvc3QgJ1I1NF8yX0dBTUVfQlVJTERTX1BBR0VfUEFTUycKJGdhbWU9RmluZC1OYW1lQ29udGFpbnMgJG1haW4gJ9CS0YvQsdGA0LDRgtGMIEdBTUUnCmlmKCEkZ2FtZSl7CiAgICBmb3JlYWNoKCRlIGluIChHZXQtRGVzYyAkbWFpbikpewogICAgICAgIHRyeXskbj0kZS5DdXJyZW50Lk5hbWU7JGN0PSRlLkN1cnJlbnQuQ29udHJvbFR5cGUuUHJvZ3JhbW1hdGljTmFtZTskcj0kZS5DdXJyZW50LkJvdW5kaW5nUmVjdGFuZ2xlfWNhdGNoe2NvbnRpbnVlfQogICAgICAgIGlmKCRuIC1hbmQgKCRuIC1tYXRjaCAnR0FNRXzQktGL0LHRgNCw0YLRjCcpKXtXcml0ZS1Ib3N0ICJSNTQyX1VJX0RJU0NPVkVSWSBuYW1lPSRuIHR5cGU9JGN0IHg9JCgkci5YKSB5PSQoJHIuWSkgdz0kKCRyLldpZHRoKSBoPSQoJHIuSGVpZ2h0KSJ9CiAgICB9Cn0KaWYoIShJbnZva2UtRWxlbWVudCAkZ2FtZSkpe3RyeXskcHJvYy5LaWxsKCl9Y2F0Y2h7fTt0aHJvdyAnUjU0LjIgR0FNRSBzZWxlY3QgYnV0dG9uIG5vdCBpbnZva2FibGUnfQonQC5UcmltKCk='
$replacement=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($b64))
$src=$src.Substring(0,$start)+$replacement+$src.Substring($end)
$tmp=Join-Path $env:RUNNER_TEMP 'r54_2_game_mutation_acceptance_v4_expanded.ps1'
Set-Content $tmp $src -Encoding UTF8
& $tmp -ArtifactDir $ArtifactDir
if($LASTEXITCODE-ne0){throw "R54.2 GAME mutation v4 failed: $LASTEXITCODE"}
